//Tuyến - Hoàn thành
package Form_JFrame_Test;

import java.text.ParseException;
import com.raven.dialog.BangMau;
import com.raven.dialog.Confirm;
import com.raven.dialog.Message;
import com.raven.main.Main;
import java.awt.Image;
import java.io.File;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import qlsmp.DAO.LoaiSPDAO;
import qlsmp.DAO.MauSacDAO;
import qlsmp.DAO.SanPhamDAO;
import qlsmp.DAO.ThuongHieuDAO;
import qlsmp.Model.LoaiSP;
import qlsmp.Model.MauSac;
import qlsmp.Model.SanPham;
import qlsmp.Model.ThuongHieu;
import qlsmp.utis.XImage;

public class SanPhamJdilog extends javax.swing.JDialog {

    /**
     * Creates new form SanPhamJdilog
     */
    public SanPhamJdilog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDS = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        hinh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxLoaiSP = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblMaSP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        cbxThuongHieu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxMau = new javax.swing.JComboBox<>();
        btnThemMau = new javax.swing.JButton();
        lblErrorGiaBan = new javax.swing.JLabel();
        lblErrorGiaNhap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        lblErrorTenSP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setText("Tên sán phẩm");

        btnSearch.setBackground(new java.awt.Color(0, 0, 102));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblDS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        hinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        hinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hinhMouseClicked(evt);
            }
        });

        jLabel2.setText("Giá bán:");

        jLabel3.setText("Thương hiệu:");

        txtGiaBan.setText("1200000");

        jLabel4.setText("Loại sản phẩm:");

        cbxLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trang điểm", "Chăm sóc da", "Nước hoa" }));
        cbxLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiSPActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 0, 102));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 0, 102));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 0, 102));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 0, 102));
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lblMaSP.setText("112");

        jLabel6.setText("Mã sản phẩm:");

        jLabel7.setText("Tên sản phẩm:");

        txtTen.setText("SON MÔI ROUGE PUR COUTURE THE SLIM VELVET RADICAL");
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        cbxThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trang điểm", "Chăm sóc da", "Nước hoa" }));
        cbxThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThuongHieuActionPerformed(evt);
            }
        });

        jLabel8.setText("Màu sắc:");

        cbxMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trang điểm", "Chăm sóc da", "Nước hoa" }));
        cbxMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMauActionPerformed(evt);
            }
        });

        btnThemMau.setBackground(new java.awt.Color(0, 0, 102));
        btnThemMau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemMau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMau.setText("+");
        btnThemMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMauActionPerformed(evt);
            }
        });

        lblErrorGiaBan.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorGiaBan.setText("Giá phải lớn hơn 1000");

        lblErrorGiaNhap.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorGiaNhap.setText("Giá phải lớn hơn 1000");

        jLabel5.setText("Giá nhập:");

        txtGiaNhap.setText("1200000");

        lblErrorTenSP.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorTenSP.setText("Tên sản phẩm đang trống");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrorGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxMau, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrorGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblErrorTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorTenSP)
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorGiaBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorGiaNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
//        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
//        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        maSPClick = 0;
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void hinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hinhMouseClicked
        chonAnh();
    }//GEN-LAST:event_hinhMouseClicked

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void cbxLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiSPActionPerformed

    private void cbxThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThuongHieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxThuongHieuActionPerformed

    private void cbxMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMauActionPerformed

    private void btnThemMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMauActionPerformed
        this.showColor();
        fillComboboxByID();
    }//GEN-LAST:event_btnThemMauActionPerformed

    private void tblDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMouseClicked
        int row = tblDS.getSelectedRow();
        maSPClick = (int) tblDS.getValueAt(row, 0);
        System.out.println("mã sản phẩm:" + maSPClick);
        SanPham sp = SPdao.selecteByID(maSPClick);
        this.setForm(sp);
        indexInsert = false;
        updateStatus();
    }//GEN-LAST:event_tblDSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamJdilog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPhamJdilog dialog = new SanPhamJdilog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMau;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxLoaiSP;
    private javax.swing.JComboBox<String> cbxMau;
    private javax.swing.JComboBox<String> cbxThuongHieu;
    private javax.swing.JLabel hinh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblErrorGiaBan;
    private javax.swing.JLabel lblErrorGiaNhap;
    private javax.swing.JLabel lblErrorTenSP;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JTable tblDS;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    public List<SanPham> list = new ArrayList<>();
    SanPhamDAO SPdao = new SanPhamDAO();
    String[] colums = {"Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Giá nhập", "Mã Vạch", "Mã loại", "Mã thương hiệu", "Hinh"};
    DefaultTableModel modelDS = new DefaultTableModel(colums, 0);
    private boolean indexInsert = false;
    private int maSPClick = 0;

    void init() {
        this.setIconImage(XImage.getApplcon());
        setLocationRelativeTo(null);
        setTitle("Quản lý sản phẩm");
        this.clearForm();
//        this.updateStatus();
        this.fillTable();
    }

    private void updateStatus() {
        btnThem.setEnabled(indexInsert);
        btnLamMoi.setEnabled(indexInsert);
        btnThemMau.setEnabled(!indexInsert);
        btnSua.setEnabled(!indexInsert);
        btnXoa.setEnabled(!indexInsert);
    }

    private void showMessage(String message) {
        Message obj = new Message(Main.getFrames()[0], true);
        obj.showMessage(message);
    }

    private boolean showConfirm(String Confirm, String message) {
        Confirm obj = new Confirm(Main.getFrames()[0], true);
        obj.showConfirm(Confirm);

        if (obj.ExitOK()) {
            this.showMessage(message);
            return true;
        } else {
            return false;
        }
    }

    private void showColor() {
        BangMau bangmau = new BangMau(Main.getFrames()[0], true);

        SanPham sp = SPdao.selecteByID(maSPClick);
        bangmau.setFormSP(sp);
        bangmau.showColor();
    }

    public void setHinhAnh(String path, JLabel hinh) {
        if (path != null) {
            ImageIcon icon = XImage.read(path);
            Image image = icon.getImage();
            Image image2 = image.getScaledInstance(111, 93, Image.SCALE_SMOOTH);
            hinh.setToolTipText(path);
            hinh.setIcon(new ImageIcon(image2));
        } else {
            hinh.setIcon(null);
        }
    }

    private void chonAnh() {
        if (FileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = FileChooser.getSelectedFile();
            XImage.save(file); // lưu hình và thư mục logos
            ImageIcon icon = XImage.read(file.getName());
            Image image = icon.getImage(); //trả về hình cho icon
            Image newImg = image.getScaledInstance(190, 152, java.awt.Image.SCALE_SMOOTH); //TẠO MỘT PHIÊN BẢN THU NHỎ, CÓ THỂ ĐIỀU CHỈNH KÍCH THƯỚC
            icon = new ImageIcon(newImg);
            hinh.setIcon(icon);
            hinh.setToolTipText(file.getName());
        }
    }

    public void clearForm() {
        txtSearch.setText(null);
        hinh.setIcon(null);
        SanPham sp = new SanPham();
        this.setForm(sp);
        indexInsert = true;
        this.updateStatus();
    }

    void fillTable() {
        list = SPdao.selectAll();
        for (SanPham sp : list) {
            modelDS.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getGiaBan(), sp.getGiaNhap(), sp.getMaVach(), sp.getMaLoai(), sp.getMaThuongHieu(), sp.getHinh()});
        }
        tblDS.setModel(modelDS);
    }

    void fillComboboxByID() {
        DefaultComboBoxModel modelLoai = new DefaultComboBoxModel();
        modelLoai.removeAllElements();
        DefaultComboBoxModel modelTH = new DefaultComboBoxModel();
        modelTH.removeAllElements();
        DefaultComboBoxModel modelMS = new DefaultComboBoxModel();
        modelMS.removeAllElements();
        if (maSPClick != 0) {
            SanPham sanPham = SPdao.selecteByID(maSPClick);
            //Loại sp
            List<LoaiSP> listLSP = new ArrayList<>();
            LoaiSPDAO loaiDAO = new LoaiSPDAO();
            listLSP = loaiDAO.selectByID(sanPham.getMaLoai());
            for (LoaiSP sp : listLSP) {
                modelLoai.addElement(sp.getTenLoai());
            }
            cbxLoaiSP.setModel(modelLoai);
            //Thương hiệu sp
            List<ThuongHieu> listTH = new ArrayList<>();
            ThuongHieuDAO THDAO = new ThuongHieuDAO();
            listTH = THDAO.selectByID(sanPham.getMaThuongHieu());
            for (ThuongHieu sp : listTH) {
                modelTH.addElement(sp.getTenTH());
            }
            cbxThuongHieu.setModel(modelTH);
            //Màu sắc sp
            List<MauSac> listMau = new ArrayList<>();
            MauSacDAO MauDAO = new MauSacDAO();
            listMau = MauDAO.selectByMaSP(maSPClick);
            for (MauSac sp : listMau) {
                modelMS.addElement(sp.getTenMau());
            }
            cbxMau.setModel(modelMS);
        } else {
            cbxLoaiSP.setModel(modelLoai);
            cbxMau.setModel(modelMS);
            cbxThuongHieu.setModel(modelTH);
        }
    }

    void setForm(SanPham sp) {
        lblMaSP.setText(sp.getMaSP() + "");
        txtTen.setText(sp.getTenSP());
        lblErrorTenSP.setVisible(false);
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");
        String formatted = decimalFormat.format(sp.getGiaBan());
        txtGiaBan.setText(formatted);
        lblErrorGiaBan.setVisible(false);

        String formatted2 = decimalFormat.format(sp.getGiaNhap());
        txtGiaNhap.setText(formatted2);
        lblErrorGiaNhap.setVisible(false);
        fillComboboxByID();
        if (sp.getHinh() != null) {
            setHinhAnh(sp.getHinh(), hinh);
        }
    }

    void getForm(SanPham sp) {
        sp.setTenSP(txtTen.getText());
        sp.setGiaBan(Double.parseDouble(txtGiaBan.getText()));
        sp.setGiaNhap(Double.parseDouble(txtGiaNhap.getText()));
        if (cbxLoaiSP.getSelectedItem().equals("Trang điểm")) {
            sp.setMaLoai(1);
        } else if (cbxLoaiSP.getSelectedItem().equals("Chăm sóc da")) {
            sp.setMaLoai(2);
        } else if (cbxLoaiSP.getSelectedItem().equals("Nước hoa")) {
            sp.setMaLoai(3);
        } else {
            return;
        }
        if (cbxThuongHieu.getSelectedItem().equals("YSL")) {
            sp.setMaThuongHieu(1);
        } else if (cbxThuongHieu.getSelectedItem().equals("Maybeline")) {
            sp.setMaThuongHieu(2);
        } else if (cbxThuongHieu.getSelectedItem().equals("The Ordinary")) {
            sp.setMaThuongHieu(3);
        } else if (cbxThuongHieu.getSelectedItem().equals("Loreal")) {
            sp.setMaThuongHieu(4);
        } else if (cbxThuongHieu.getSelectedItem().equals("Innisfree")) {
            sp.setMaThuongHieu(5);
        } else {
            return;
        }
    }

    void check() {
        if (txtTen.getText().isBlank()) {
            lblErrorTenSP.setText("Vui lòng nhập tên sản phẩm.");
            lblErrorTenSP.setVisible(true);
            return;
        } else if (txtGiaBan.getText().isBlank()) {
            lblErrorGiaBan.setText("Vui lòng nhập giá bán.");
            lblErrorGiaBan.setVisible(true);
            return;
        } else if (txtGiaNhap.getText().isBlank()) {
            txtGiaNhap.setText("Vui lòng nhập giá nhập.");
            txtGiaNhap.setVisible(true);
            return;
        }
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.00");
        try {
            Number parsedNumber = decimalFormat.parse(txtGiaBan.getText());
            double result = parsedNumber.doubleValue();
            if (result < 1000) {
                lblErrorGiaBan.setText("Giá bán phải lớn hơn 1000.");
                lblErrorGiaBan.setVisible(true);
                return;
            }
        } catch (ParseException e) {
            lblErrorGiaBan.setText("Giá bán không đúng định dạng.");
            lblErrorGiaBan.setVisible(true);
            e.printStackTrace();
            return;
        }
        try {
            Number parsedNumber = decimalFormat.parse(txtGiaNhap.getText());
            double result = parsedNumber.doubleValue();
            if (result < 1000) {
                lblErrorGiaNhap.setText("Giá bán phải lớn hơn 1000.");
                lblErrorGiaNhap.setVisible(true);
                return;
            }
        } catch (ParseException e) {
            lblErrorGiaNhap.setText("Giá bán không đúng định dạng.");
            lblErrorGiaNhap.setVisible(true);
            e.printStackTrace();
            return;
        }
    }

    void insert() {

    }

    void search() {
        list = SPdao.selectByKeyword(txtSearch.getText());
        modelDS.setRowCount(0);
        tblDS.setModel(modelDS);
        for (SanPham sp : list) {
            modelDS.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getGiaBan(), sp.getGiaNhap(), sp.getMaVach(), sp.getMaLoai(), sp.getMaThuongHieu(), sp.getHinh()});
        }
        tblDS.setModel(modelDS);
    }
}
